const Homeproduct = 
[
    {
        id: 1,
        Name: 'Xiaomi Redmi 12 (Polar Silver) ',
        price: '41990.00',
        image: 'images/p1.png',
        cat: 'Mobile',
        type : 'top',
    },
    {
        id: 2,
        Name: 'Samsung Galaxy S23 Ultra ',
        price: ' 228000.00 ',
        image: 'images/p2.webp',
        cat: 'Mobile',
        type : 'new',
    },
    {
        id: 3,
        Name: 'Apple AirPods 4 (2024)',
        price: '54000.00',
        image: 'images/p3.jpg',
        cat: 'Accessories',
        type : 'top',
    },
    {
        id: 4,
        Name: 'Samsung Galaxy Watch 6',
        price: '84000.00',
        image: 'images/p4.webp',
        cat: 'Watch',
        type : 'new',
    },
    {
        id: 5,
        Name: 'Mobile Game Triggers',
        price: '450.00',
        image: 'images/p5.jpg',
        cat: 'Accessories',
        type : 'top',
    },
    {
        id: 6,
        Name: '45W Ultra Fast Charger',
        price: '6500.00',
        image: 'images/p6.webp',
        cat: 'Electronics',
        type : 'new',
    },
    {
        id: 7,
        Name: 'IPhone Transparent BackCover',
        price: '1300.00',
        image: 'images/p7.webp',
        cat: 'Accessories',
        type : 'featured',
    },
    {
        id: 8,
        Name: 'JBL Bluetooth Speaker',
        price: '6000.00',
        image: 'images/p8.webp',
        cat: 'Speaker',
        type : 'featured',
    },
    {
        id: 9,
        Name: 'USB Pen Drive 3.0(128), SD Cards',
        price: '3100.00',
        image: 'images/p9.jpg',
        cat: 'Electronics',
        type : 'new',
    },
    {
        id: 10,
        Name: 'Mobile Charging Port Cleaning Kit',
        price: '8300.00',
        image: 'images/p10.jpg',
        cat: 'Accessories',
        type : 'featured',
    },
    {
        id:11,
        Name: 'Mobile Mount and Holder',
        price: '900.00',
        image: 'images/p11.jpg',
        cat: 'Accessories',
        type : 'featured',
    },
    {
        id: 12,
        Name: 'Promate EcoLight Solar Power Bank',
        price: '25000.00',
        image: 'images/p12.jpg',
        cat: 'Electronics',
        type : 'top',
    },
]
export default Homeproduct